force-app/main/default/objects/Llamada_API__c/Llamada_API__c.object-meta.xml
<CustomObject>
    <label>Llamada API</label>
    <nameField>
        <displayFormat>LLA-{0000}</displayFormat>
        <label>Nombre de Llamada API</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Llamadas API</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Llamada_API__c/fields/C_digo_respuesta__c.field-meta.xml
<CustomField>
    <fullName>C_digo_respuesta__c</fullName>
    <label>Código respuesta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Llamada_API__c/fields/Con_error__c.field-meta.xml
<CustomField>
    <fullName>Con_error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Con error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Llamada_API__c/fields/Respuesta__c.field-meta.xml
<CustomField>
    <fullName>Respuesta__c</fullName>
    <label>Respuesta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Llamada_API__c/fields/Solicitud__c.field-meta.xml
<CustomField>
    <fullName>Solicitud__c</fullName>
    <label>Solicitud</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MPSubscriptionTest.cls
@isTest
private class MPSubscriptionTest {
    @isTest
    static void  testCancelSubscriptionSuccess() {
        Test.setMock(HttpCalloutMock.class, new MPSubscriptionCalloutMock());

        List<InputVariableSubscriptionClass> inputVariables = new List<InputVariableSubscriptionClass>();
        InputVariableSubscriptionClass inputItem = new InputVariableSubscriptionClass();
        inputItem.action = 'cancel';
        inputItem.subscriptionId = 'SubsOk';
        inputVariables.add(inputItem);

        Test.startTest();
        List<OutputVariableSubscriptionClass> response= MPSubscriptionController.cancelOrPauseSubscription(inputVariables);
        Test.stopTest();
		
        Llamada_API__c[] apiRecord = [SELECT C_digo_respuesta__c, Solicitud__c, Con_error__c, Respuesta__c FROM Llamada_API__c LIMIT 1];
        System.assertEquals(response[0].status, 'success');
        System.assertEquals(apiRecord[0].C_digo_respuesta__c, 200);
		System.assertEquals(apiRecord[0].Con_error__c, false);
		System.assertEquals(apiRecord[0].Respuesta__c, '{"id": "SubsOk" }');
        System.assertEquals(apiRecord[0].Solicitud__c, '{"status":"cancelled"}');
    }
    
    @isTest
    static void  testPauseSubscriptionSuccess() {
        Test.setMock(HttpCalloutMock.class, new MPSubscriptionCalloutMock());

        List<InputVariableSubscriptionClass> inputVariables = new List<InputVariableSubscriptionClass>();
        InputVariableSubscriptionClass inputItem = new InputVariableSubscriptionClass();
        inputItem.action = 'pause';
        inputItem.subscriptionId = 'SubsOk';
        inputVariables.add(inputItem);

        Test.startTest();
        List<OutputVariableSubscriptionClass> response= MPSubscriptionController.cancelOrPauseSubscription(inputVariables);
        Test.stopTest();
		
        Llamada_API__c[] apiRecord = [SELECT C_digo_respuesta__c, Solicitud__c, Con_error__c, Respuesta__c FROM Llamada_API__c LIMIT 1];
        System.assertEquals(response[0].status, 'success');
        System.assertEquals(apiRecord[0].C_digo_respuesta__c, 200);
		System.assertEquals(apiRecord[0].Con_error__c, false);
		System.assertEquals(apiRecord[0].Respuesta__c, '{"id": "SubsOk" }');
        System.assertEquals(apiRecord[0].Solicitud__c, '{"status":"paused"}');
    }
    
    @isTest
    static void  testCancelSubscriptionError() {
        Test.setMock(HttpCalloutMock.class, new MPSubscriptionCalloutMock());

        List<InputVariableSubscriptionClass> inputVariables = new List<InputVariableSubscriptionClass>();
        InputVariableSubscriptionClass inputItem = new InputVariableSubscriptionClass();
        inputItem.action = 'cancel';
        inputItem.subscriptionId = 'SubErr';
        inputVariables.add(inputItem);

        Test.startTest();
        List<OutputVariableSubscriptionClass> response= MPSubscriptionController.cancelOrPauseSubscription(inputVariables);
        Test.stopTest();
		
        Llamada_API__c[] apiRecord = [SELECT C_digo_respuesta__c, Solicitud__c, Con_error__c, Respuesta__c FROM Llamada_API__c LIMIT 1];
        System.assertEquals(response[0].status, 'error');
        System.assertEquals(apiRecord[0].C_digo_respuesta__c, 500);
		System.assertEquals(apiRecord[0].Con_error__c, true);
		System.assertEquals(apiRecord[0].Respuesta__c, 'Error updating the subscription');
        System.assertEquals(apiRecord[0].Solicitud__c, '{"status":"cancelled"}');
    }
    
    @isTest
    static void  testPauseSubscriptionError() {
        Test.setMock(HttpCalloutMock.class, new MPSubscriptionCalloutMock());

        List<InputVariableSubscriptionClass> inputVariables = new List<InputVariableSubscriptionClass>();
        InputVariableSubscriptionClass inputItem = new InputVariableSubscriptionClass();
        inputItem.action = 'pause';
        inputItem.subscriptionId = 'SubErr';
        inputVariables.add(inputItem);

        Test.startTest();
        List<OutputVariableSubscriptionClass> response= MPSubscriptionController.cancelOrPauseSubscription(inputVariables);
        Test.stopTest();
		
        Llamada_API__c[] apiRecord = [SELECT C_digo_respuesta__c, Solicitud__c, Con_error__c, Respuesta__c FROM Llamada_API__c LIMIT 1];
        System.assertEquals(response[0].status, 'error');
        System.assertEquals(apiRecord[0].C_digo_respuesta__c, 500);
		System.assertEquals(apiRecord[0].Con_error__c, true);
		System.assertEquals(apiRecord[0].Respuesta__c, 'Error updating the subscription');
        System.assertEquals(apiRecord[0].Solicitud__c, '{"status":"paused"}');
    }
    
    @isTest
    static void  testCancelSubscriptionException() {
        Test.setMock(HttpCalloutMock.class, new MPSubscriptionCalloutMock());

        List<InputVariableSubscriptionClass> inputVariables = new List<InputVariableSubscriptionClass>();
        InputVariableSubscriptionClass inputItem = new InputVariableSubscriptionClass();
        inputItem.action = 'cancel';
        inputItem.subscriptionId = 'SubExc';
        inputVariables.add(inputItem);

        Test.startTest();
        List<OutputVariableSubscriptionClass> response= MPSubscriptionController.cancelOrPauseSubscription(inputVariables);
        Test.stopTest();
		
        Llamada_API__c[] apiRecord = [SELECT C_digo_respuesta__c, Solicitud__c, Con_error__c, Respuesta__c FROM Llamada_API__c LIMIT 1];
        System.assertEquals(response[0].status, 'error');
        System.assertEquals(apiRecord[0].C_digo_respuesta__c, null);
		System.assertEquals(apiRecord[0].Con_error__c, true);
		System.assertEquals(apiRecord[0].Respuesta__c.contains('Error Server updating subscription'), true);
        System.assertEquals(apiRecord[0].Solicitud__c, '{"status":"cancelled"}');
    }
    
    @isTest
    static void  testGetSubscriptionSuccess() {
        Test.setMock(HttpCalloutMock.class, new MPSubscriptionCalloutMock());
		String Id = 'SubsOk';
 
        Test.startTest();
        Map<String, Object> resp = MPSubscriptionController.getMPSubscription(Id);
        Test.stopTest();
		
        System.assertEquals(resp.get('status'), 'success');
		System.assertEquals(resp.get('body').toString(), '{id=SubsOk}');
		System.assertEquals(resp.containsKey('llamadaApi'), true);
    }
    
    @isTest
    static void  testGetSubscriptionError() {
        Test.setMock(HttpCalloutMock.class, new MPSubscriptionCalloutMock());
		String Id = 'SubErr';
 
        Test.startTest();
        Map<String, Object> resp = MPSubscriptionController.getMPSubscription(Id);
        Test.stopTest();
		
        System.assertEquals(resp.get('status'), 'error');
		System.assertEquals((resp.get('message').toString()).contains('Error getting the subscription'), true);
		System.assertEquals(resp.containsKey('llamadaApi'), true);
    }
    
    @isTest
    static void  testGetSubscriptionExc() {
        Test.setMock(HttpCalloutMock.class, new MPSubscriptionCalloutMock());
		String Id = 'SubExc';
 
        Test.startTest();
        Map<String, Object> resp = MPSubscriptionController.getMPSubscription(Id);
        Test.stopTest();
		
        System.assertEquals(resp.get('status'), 'error');
		System.assertEquals(resp.get('message').toString(), 'Error getting the subscription');
		System.assertEquals(resp.containsKey('llamadaApi'), true);
    }
}